services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80" # Map host port 80 to container port 80
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/headers.conf:/etc/nginx/headers.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
    networks:
      - frontend_network

networks:
  frontend_network:
    external: true