services:
  web:
    image: nginx:latest
    container_name: web
    # ports:
    #   - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: always
    networks:
      - frontend_network
    
networks:
  frontend_network:
    external: true